/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KeyFactor = IDL.Record({
  'impactScore' : IDL.Float64,
  'factorName' : IDL.Text,
});
export const Decision = IDL.Variant({
  'underReview' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const PredictionResult = IDL.Record({
  'keyFactors' : IDL.Vec(KeyFactor),
  'decision' : Decision,
  'approvalLikelihood' : IDL.Float64,
});
export const EmploymentStatus = IDL.Variant({
  'unemployed' : IDL.Null,
  'employed' : IDL.Null,
  'selfEmployed' : IDL.Null,
});
export const EducationLevel = IDL.Variant({
  'highSchool' : IDL.Null,
  'bachelor' : IDL.Null,
  'master' : IDL.Null,
  'doctorate' : IDL.Null,
});
export const LoanApplication = IDL.Record({
  'age' : IDL.Nat,
  'loanTermMonths' : IDL.Nat,
  'loanAmount' : IDL.Float64,
  'name' : IDL.Text,
  'annualIncome' : IDL.Float64,
  'numDependents' : IDL.Nat,
  'creditScore' : IDL.Nat,
  'monthlyDebt' : IDL.Float64,
  'employmentStatus' : EmploymentStatus,
  'educationLevel' : EducationLevel,
});
export const Time = IDL.Int;
export const PredictionRecord = IDL.Record({
  'result' : PredictionResult,
  'applicant' : IDL.Principal,
  'application' : LoanApplication,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getPredictionHistory' : IDL.Func([], [IDL.Vec(PredictionRecord)], ['query']),
  'submitApplication' : IDL.Func([LoanApplication], [PredictionResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KeyFactor = IDL.Record({
    'impactScore' : IDL.Float64,
    'factorName' : IDL.Text,
  });
  const Decision = IDL.Variant({
    'underReview' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const PredictionResult = IDL.Record({
    'keyFactors' : IDL.Vec(KeyFactor),
    'decision' : Decision,
    'approvalLikelihood' : IDL.Float64,
  });
  const EmploymentStatus = IDL.Variant({
    'unemployed' : IDL.Null,
    'employed' : IDL.Null,
    'selfEmployed' : IDL.Null,
  });
  const EducationLevel = IDL.Variant({
    'highSchool' : IDL.Null,
    'bachelor' : IDL.Null,
    'master' : IDL.Null,
    'doctorate' : IDL.Null,
  });
  const LoanApplication = IDL.Record({
    'age' : IDL.Nat,
    'loanTermMonths' : IDL.Nat,
    'loanAmount' : IDL.Float64,
    'name' : IDL.Text,
    'annualIncome' : IDL.Float64,
    'numDependents' : IDL.Nat,
    'creditScore' : IDL.Nat,
    'monthlyDebt' : IDL.Float64,
    'employmentStatus' : EmploymentStatus,
    'educationLevel' : EducationLevel,
  });
  const Time = IDL.Int;
  const PredictionRecord = IDL.Record({
    'result' : PredictionResult,
    'applicant' : IDL.Principal,
    'application' : LoanApplication,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getPredictionHistory' : IDL.Func(
        [],
        [IDL.Vec(PredictionRecord)],
        ['query'],
      ),
    'submitApplication' : IDL.Func([LoanApplication], [PredictionResult], []),
  });
};

export const init = ({ IDL }) => { return []; };