/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Decision = { 'underReview' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export type EducationLevel = { 'highSchool' : null } |
  { 'bachelor' : null } |
  { 'master' : null } |
  { 'doctorate' : null };
export type EmploymentStatus = { 'unemployed' : null } |
  { 'employed' : null } |
  { 'selfEmployed' : null };
export interface KeyFactor { 'impactScore' : number, 'factorName' : string }
export interface LoanApplication {
  'age' : bigint,
  'loanTermMonths' : bigint,
  'loanAmount' : number,
  'name' : string,
  'annualIncome' : number,
  'numDependents' : bigint,
  'creditScore' : bigint,
  'monthlyDebt' : number,
  'employmentStatus' : EmploymentStatus,
  'educationLevel' : EducationLevel,
}
export interface PredictionRecord {
  'result' : PredictionResult,
  'applicant' : Principal,
  'application' : LoanApplication,
  'timestamp' : Time,
}
export interface PredictionResult {
  'keyFactors' : Array<KeyFactor>,
  'decision' : Decision,
  'approvalLikelihood' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'getPredictionHistory' : ActorMethod<[], Array<PredictionRecord>>,
  'submitApplication' : ActorMethod<[LoanApplication], PredictionResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];