/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface PredictionResult {
    keyFactors: Array<KeyFactor>;
    decision: Decision;
    approvalLikelihood: number;
}
export interface LoanApplication {
    age: bigint;
    loanTermMonths: bigint;
    loanAmount: number;
    name: string;
    annualIncome: number;
    numDependents: bigint;
    creditScore: bigint;
    monthlyDebt: number;
    employmentStatus: EmploymentStatus;
    educationLevel: EducationLevel;
}
export interface KeyFactor {
    impactScore: number;
    factorName: string;
}
export interface PredictionRecord {
    result: PredictionResult;
    applicant: Principal;
    application: LoanApplication;
    timestamp: Time;
}
export enum Decision {
    underReview = "underReview",
    denied = "denied",
    approved = "approved"
}
export enum EducationLevel {
    highSchool = "highSchool",
    bachelor = "bachelor",
    master = "master",
    doctorate = "doctorate"
}
export enum EmploymentStatus {
    unemployed = "unemployed",
    employed = "employed",
    selfEmployed = "selfEmployed"
}
export interface backendInterface {
    getPredictionHistory(): Promise<Array<PredictionRecord>>;
    submitApplication(application: LoanApplication): Promise<PredictionResult>;
}
import type { Decision as _Decision, EducationLevel as _EducationLevel, EmploymentStatus as _EmploymentStatus, KeyFactor as _KeyFactor, LoanApplication as _LoanApplication, PredictionRecord as _PredictionRecord, PredictionResult as _PredictionResult, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getPredictionHistory(): Promise<Array<PredictionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionHistory();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionHistory();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitApplication(arg0: LoanApplication): Promise<PredictionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(to_candid_LoanApplication_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PredictionResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(to_candid_LoanApplication_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PredictionResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Decision_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Decision): Decision {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_EducationLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationLevel): EducationLevel {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_EmploymentStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentStatus): EmploymentStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_LoanApplication_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanApplication): LoanApplication {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PredictionRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictionRecord): PredictionRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PredictionResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictionResult): PredictionResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: _PredictionResult;
    applicant: Principal;
    application: _LoanApplication;
    timestamp: _Time;
}): {
    result: PredictionResult;
    applicant: Principal;
    application: LoanApplication;
    timestamp: Time;
} {
    return {
        result: from_candid_PredictionResult_n4(_uploadFile, _downloadFile, value.result),
        applicant: value.applicant,
        application: from_candid_LoanApplication_n8(_uploadFile, _downloadFile, value.application),
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    keyFactors: Array<_KeyFactor>;
    decision: _Decision;
    approvalLikelihood: number;
}): {
    keyFactors: Array<KeyFactor>;
    decision: Decision;
    approvalLikelihood: number;
} {
    return {
        keyFactors: value.keyFactors,
        decision: from_candid_Decision_n6(_uploadFile, _downloadFile, value.decision),
        approvalLikelihood: value.approvalLikelihood
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    loanTermMonths: bigint;
    loanAmount: number;
    name: string;
    annualIncome: number;
    numDependents: bigint;
    creditScore: bigint;
    monthlyDebt: number;
    employmentStatus: _EmploymentStatus;
    educationLevel: _EducationLevel;
}): {
    age: bigint;
    loanTermMonths: bigint;
    loanAmount: number;
    name: string;
    annualIncome: number;
    numDependents: bigint;
    creditScore: bigint;
    monthlyDebt: number;
    employmentStatus: EmploymentStatus;
    educationLevel: EducationLevel;
} {
    return {
        age: value.age,
        loanTermMonths: value.loanTermMonths,
        loanAmount: value.loanAmount,
        name: value.name,
        annualIncome: value.annualIncome,
        numDependents: value.numDependents,
        creditScore: value.creditScore,
        monthlyDebt: value.monthlyDebt,
        employmentStatus: from_candid_EmploymentStatus_n10(_uploadFile, _downloadFile, value.employmentStatus),
        educationLevel: from_candid_EducationLevel_n12(_uploadFile, _downloadFile, value.educationLevel)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unemployed: null;
} | {
    employed: null;
} | {
    selfEmployed: null;
}): EmploymentStatus {
    return "unemployed" in value ? EmploymentStatus.unemployed : "employed" in value ? EmploymentStatus.employed : "selfEmployed" in value ? EmploymentStatus.selfEmployed : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    highSchool: null;
} | {
    bachelor: null;
} | {
    master: null;
} | {
    doctorate: null;
}): EducationLevel {
    return "highSchool" in value ? EducationLevel.highSchool : "bachelor" in value ? EducationLevel.bachelor : "master" in value ? EducationLevel.master : "doctorate" in value ? EducationLevel.doctorate : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    underReview: null;
} | {
    denied: null;
} | {
    approved: null;
}): Decision {
    return "underReview" in value ? Decision.underReview : "denied" in value ? Decision.denied : "approved" in value ? Decision.approved : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PredictionRecord>): Array<PredictionRecord> {
    return value.map((x)=>from_candid_PredictionRecord_n2(_uploadFile, _downloadFile, x));
}
function to_candid_EducationLevel_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationLevel): _EducationLevel {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_EmploymentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentStatus): _EmploymentStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_LoanApplication_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanApplication): _LoanApplication {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    loanTermMonths: bigint;
    loanAmount: number;
    name: string;
    annualIncome: number;
    numDependents: bigint;
    creditScore: bigint;
    monthlyDebt: number;
    employmentStatus: EmploymentStatus;
    educationLevel: EducationLevel;
}): {
    age: bigint;
    loanTermMonths: bigint;
    loanAmount: number;
    name: string;
    annualIncome: number;
    numDependents: bigint;
    creditScore: bigint;
    monthlyDebt: number;
    employmentStatus: _EmploymentStatus;
    educationLevel: _EducationLevel;
} {
    return {
        age: value.age,
        loanTermMonths: value.loanTermMonths,
        loanAmount: value.loanAmount,
        name: value.name,
        annualIncome: value.annualIncome,
        numDependents: value.numDependents,
        creditScore: value.creditScore,
        monthlyDebt: value.monthlyDebt,
        employmentStatus: to_candid_EmploymentStatus_n16(_uploadFile, _downloadFile, value.employmentStatus),
        educationLevel: to_candid_EducationLevel_n18(_uploadFile, _downloadFile, value.educationLevel)
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentStatus): {
    unemployed: null;
} | {
    employed: null;
} | {
    selfEmployed: null;
} {
    return value == EmploymentStatus.unemployed ? {
        unemployed: null
    } : value == EmploymentStatus.employed ? {
        employed: null
    } : value == EmploymentStatus.selfEmployed ? {
        selfEmployed: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationLevel): {
    highSchool: null;
} | {
    bachelor: null;
} | {
    master: null;
} | {
    doctorate: null;
} {
    return value == EducationLevel.highSchool ? {
        highSchool: null
    } : value == EducationLevel.bachelor ? {
        bachelor: null
    } : value == EducationLevel.master ? {
        master: null
    } : value == EducationLevel.doctorate ? {
        doctorate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
